#!/usr/bin/env bash
# Mimic `pmset -g batt` output.
if [ -n "${MOCK_PMSET_EMPTY:-}" ]; then
    exit 0
fi
if [ "${MOCK_BATT_AC:-0}" -eq 1 ]; then
    echo "Now drawing from 'AC Power'"
    echo " -InternalBattery-0 (id=0)	${MOCK_BATT_PCT:-100}%; charging; 0:00 remaining present: true"
else
    echo "Now drawing from 'Battery Power'"
    echo " -InternalBattery-0 (id=0)	${MOCK_BATT_PCT:-50}%; discharging; 1:00 remaining present: true"
fi
